jms_serializer:
    handlers:
        datetime:
            default_format: 'd/m/Y H:i:s'
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
    visitors:
        xml:
            format_output: '%kernel.debug%'
        json:
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
